In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/bouissacludivine/DESKTOP/ProjectInterPromo/data/ECHANTILLONS/ECHANTILLON10/echantillon10.csv")

In [4]:
print(df)

                                ID  TOP_FRAUDE  TOP_FRAUDE_CARTE  \
0      831KFcsZovqRwkmyqAJhBfPGA==           1                 1
1      835qrimyjXd7SPpng/cWuEz/w==           1                 1
2      8353Z+loQUqfodVSdCZp3naCg==           1                 0
3      831rqXmvv7DhGKOKHAmM/3tGw==           1                 0
4      835M+SkL1tyzkjT6KCrMZlkNg==           1                 0
...                            ...         ...               ...
84930  835Lc+970tiDoDBovevaK4LYA==           0                 0
84931  835a1IzTiIqW+DZI7N0vRVW5A==           0                 0
84932  835cKBDV4caS5EOVeLxdsRZLQ==           0                 0
84933  835CKVu+z3oofUX0nmQlmhgPw==           0                 0
84934  835tPFj77Rqvv86c8MdZTvwJg==           0                 0

       TOP_FRAUDE_VIREMENT Date_debut_fraude cp_ou_pays  \
0                        0         07JUL2020      SÎUVf
1                        0               NaN      céyaÏ
2                        1               NaN      tîêÅÊ
3                        1         15OCT2020      æËYJ3
4                        1               NaN      céÎYG
...                    ...               ...        ...
84930                    0               NaN      gíÇXN
84931                    0               NaN      çÊpÀu
84932                    0               NaN      ïÎkhw
84933                    0               NaN      ÍlPFE
84934                    0               NaN      P2PWÅ

                       SECTEUR_GESTION    INDICMAIL    INDICTEL    INDICPOR  \
0                        SECTEUR OUEST   MAIL_OPTIN  TEL_NEUTRE   POR_OPTIN
1                     SECTEUR ALES CVN   MAIL_OPTIN   TEL_OPTIN  POR_OPTOUT
2              SECTEUR VALLEE DU RHONE  MAIL_OPTOUT   TEL_OPTIN  POR_OPTOUT
3                        SECTEUR OUEST  MAIL_OPTOUT   TEL_OPTIN  POR_OPTOUT
4                      SECTEUR BEZIERS   MAIL_OPTIN   TEL_OPTIN   POR_OPTIN
...                                ...          ...         ...         ...
84930  SECTEUR MONTPELLIER PIC ST LOUP   MAIL_OPTIN  TEL_OPTOUT   POR_OPTIN
84931                 SECTEUR NARBONNE  MAIL_NEUTRE   TEL_OPTIN   POR_OPTIN
84932                  SECTEUR BEZIERS  MAIL_NEUTRE   TEL_OPTIN  POR_NEUTRE
84933                  SECTEUR BEZIERS  MAIL_NEUTRE   TEL_OPTIN  POR_NEUTRE
84934        SECTEUR BEAUCAIROIS UZEGE  MAIL_NEUTRE   TEL_OPTIN  POR_NEUTRE

       ... mt_factu_ttc_M mt_factu_ttc_M6  mt_reduc_ttc_M  mt_reduc_ttc_M6  \
0      ...          -46.0           130.0             0.0              0.0
1      ...            7.0             6.0             0.0              0.0
2      ...            0.0             0.0             0.0              0.0
3      ...            2.0             2.0             0.0              0.0
4      ...           28.0             6.0             0.0              0.0
...    ...            ...             ...             ...              ...
84930  ...           47.0             5.0             0.0              0.0
84931  ...            6.0             6.0             0.0              0.0
84932  ...            8.0             8.0             0.0              0.0
84933  ...            6.0             6.0             0.0              0.0
84934  ...            NaN             NaN             NaN              NaN

       mt_rist_ttc_M  mt_rist_ttc_M6  Fidelite_calcule  Flag_bq_principale  \
0                0.0             0.0                FI                 1.0
1                0.0             0.0                QF                 1.0
2                0.0             0.0                NF                 0.0
3                0.0             0.0                FI                 1.0
4                0.0             0.0                FI                 1.0
...              ...             ...               ...                 ...
84930            0.0             0.0                QF                 1.0
84931            0.0             0.0                QF                 1.0
84932            0.0             0.0                FI                 1.0
84933            0.0             0.0                NF                 0.0
84934            NaN             NaN               NaN                 NaN

                     profil  localisation
0               Digital Web      toulouse
1              Full digital     languedoc
2      Peu actifs Ma banque     languedoc
3        Digital Web modéré      toulouse
4              Hyper actifs     languedoc
...                     ...           ...
84930    Digital Web modéré     languedoc
84931          sans contact     languedoc
84932       Très peu actifs     languedoc
84933       Très peu actifs     languedoc
84934          sans contact     languedoc

[84935 rows x 288 columns]

In [5]:
df.columns

Index(['ID', 'TOP_FRAUDE', 'TOP_FRAUDE_CARTE', 'TOP_FRAUDE_VIREMENT',
       'Date_debut_fraude', 'cp_ou_pays', 'SECTEUR_GESTION', 'INDICMAIL',
       'INDICTEL', 'INDICPOR',
       ...
       'mt_factu_ttc_M', 'mt_factu_ttc_M6', 'mt_reduc_ttc_M',
       'mt_reduc_ttc_M6', 'mt_rist_ttc_M', 'mt_rist_ttc_M6',
       'Fidelite_calcule', 'Flag_bq_principale', 'profil', 'localisation'],
      dtype='object', length=288)

In [6]:
type(df.columns)

pandas.core.indexes.base.Index

In [7]:
save_type = []
for i in df.columns:
    save_type.append(type(df[i][0]))

In [8]:
save_type

[str,
 numpy.int64,
 numpy.int64,
 numpy.int64,
 str,
 str,
 str,
 str,
 str,
 str,
 str,
 str,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 str,
 str,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 str,
 numpy.float64,
 numpy.float64,
 str,
 numpy.float64,
 numpy.float64,
 str,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 str,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 str,
 float,
 str,
 float,
 numpy.float64,
 numpy.float64,
 str,
 float,
 str,
 float,
 str,
 float,
 str,
 str,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 str,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 str,
 numpy.float64,
 str,
 str]

In [9]:
import numpy
liste=['<class \'str\'>']
eliminer=[]
for i in df.columns:
    save_type.append(type(df[i][0]))
for i in df.columns:
    if type(df[i][0]) == save_type[0]:
        eliminer.append(i)
eliminer

['ID',
 'Date_debut_fraude',
 'cp_ou_pays',
 'SECTEUR_GESTION',
 'INDICMAIL',
 'INDICTEL',
 'INDICPOR',
 'INDICSMS',
 'INDICMAILING',
 'DUREE_CNX_WEB_TOT_6M',
 'DUREE_CNX_MOY_WEB_6M',
 'TAUX_LECTURE_PAP_6M',
 'TAUX_LECTURE_EMAIL_6M',
 'TAUX_LECTURE_MS_6M',
 'seg_nature_potentiel',
 'type_residence_1',
 'situ_fam_1',
 'contrat_travail_1',
 'Tranche_age_1',
 'sexe_1',
 'Tranche_age_moyen',
 'situ_globale',
 'SGMT_FIDELITE',
 'Fidelite_calcule',
 'profil',
 'localisation']

In [10]:
len(eliminer), len(df.columns)

(26, 288)

In [11]:
df_quanti = df.drop([i for i in eliminer],axis=1)
df_quanti

,TOP_FRAUDE,TOP_FRAUDE_CARTE,TOP_FRAUDE_VIREMENT,TOP_E_RELEVE,MESSAGERIE_WEB_ACTIVE,FIAB_TEL_DOMICILE,FIAB_TEL_TRAVAIL,FIAB_TEL_PORTABLE,FIAB_EMAIL,REFUS_SEA,...,top_produit_Credit,top_produit_Epargne,top_produit_Services,mt_factu_ttc_M,mt_factu_ttc_M6,mt_reduc_ttc_M,mt_reduc_ttc_M6,mt_rist_ttc_M,mt_rist_ttc_M6,Flag_bq_principale
0,1,1,0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,...,1.0,1.0,1.0,-46.0,130.0,0.0,0.0,0.0,0.0,1.0
1,1,1,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,7.0,6.0,0.0,0.0,0.0,0.0,1.0
2,1,0,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,0,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0
4,1,0,1,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1.0,1.0,1.0,28.0,6.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84930,0,0,0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,47.0,5.0,0.0,0.0,0.0,0.0,1.0
84931,0,0,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,6.0,6.0,0.0,0.0,0.0,0.0,1.0
84932,0,0,0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,8.0,8.0,0.0,0.0,0.0,0.0,1.0
84933,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0
84934,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df_quanti.columns

Index(['TOP_FRAUDE', 'TOP_FRAUDE_CARTE', 'TOP_FRAUDE_VIREMENT', 'TOP_E_RELEVE',
       'MESSAGERIE_WEB_ACTIVE', 'FIAB_TEL_DOMICILE', 'FIAB_TEL_TRAVAIL',
       'FIAB_TEL_PORTABLE', 'FIAB_EMAIL', 'REFUS_SEA',
       ...
       'top_produit_Credit', 'top_produit_Epargne', 'top_produit_Services',
       'mt_factu_ttc_M', 'mt_factu_ttc_M6', 'mt_reduc_ttc_M',
       'mt_reduc_ttc_M6', 'mt_rist_ttc_M', 'mt_rist_ttc_M6',
       'Flag_bq_principale'],
      dtype='object', length=262)

In [15]:
Y = df_quanti['TOP_FRAUDE']
Y

0        1
1        1
2        1
3        1
4        1
        ..
84930    0
84931    0
84932    0
84933    0
84934    0
Name: TOP_FRAUDE, Length: 84935, dtype: int64

In [22]:
X = df_quanti.drop('TOP_FRAUDE',axis=1)
X

,TOP_FRAUDE_CARTE,TOP_FRAUDE_VIREMENT,TOP_E_RELEVE,MESSAGERIE_WEB_ACTIVE,FIAB_TEL_DOMICILE,FIAB_TEL_TRAVAIL,FIAB_TEL_PORTABLE,FIAB_EMAIL,REFUS_SEA,NBJ_CNT_AGENCE_DEPOT_6M,...,top_produit_Credit,top_produit_Epargne,top_produit_Services,mt_factu_ttc_M,mt_factu_ttc_M6,mt_reduc_ttc_M,mt_reduc_ttc_M6,mt_rist_ttc_M,mt_rist_ttc_M6,Flag_bq_principale
0,1,0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,1.0,1.0,-46.0,130.0,0.0,0.0,0.0,0.0,1.0
1,1,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,1.0,1.0,7.0,6.0,0.0,0.0,0.0,0.0,1.0
2,0,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0
4,0,1,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,1.0,28.0,6.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84930,0,0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,6.0,...,1.0,0.0,1.0,47.0,5.0,0.0,0.0,0.0,0.0,1.0
84931,0,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,6.0,6.0,0.0,0.0,0.0,0.0,1.0
84932,0,0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,8.0,8.0,0.0,0.0,0.0,0.0,1.0
84933,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0
84934,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
X = X.drop(['TOP_FRAUDE_CARTE','TOP_FRAUDE_VIREMENT'], axis=1)

In [24]:
X

,TOP_E_RELEVE,MESSAGERIE_WEB_ACTIVE,FIAB_TEL_DOMICILE,FIAB_TEL_TRAVAIL,FIAB_TEL_PORTABLE,FIAB_EMAIL,REFUS_SEA,NBJ_CNT_AGENCE_DEPOT_6M,NBJ_CNT_AGENCE_VENTE_6M,NBJ_CNT_RDV_AGENCE_6M,...,top_produit_Credit,top_produit_Epargne,top_produit_Services,mt_factu_ttc_M,mt_factu_ttc_M6,mt_reduc_ttc_M,mt_reduc_ttc_M6,mt_rist_ttc_M,mt_rist_ttc_M6,Flag_bq_principale
0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,-46.0,130.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,7.0,6.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0
4,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,28.0,6.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84930,1.0,1.0,1.0,0.0,1.0,1.0,0.0,6.0,0.0,0.0,...,1.0,0.0,1.0,47.0,5.0,0.0,0.0,0.0,0.0,1.0
84931,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,6.0,6.0,0.0,0.0,0.0,0.0,1.0
84932,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,1.0,1.0,1.0,8.0,8.0,0.0,0.0,0.0,0.0,1.0
84933,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0
84934,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
import numpy as np
corre = lambda x : np.corrcoef(x,Y)